{
  "formatVersion": "1.1",
  "component": {
    "group": "org.lsposed.lsplant",
    "module": "lsplant",
    "version": "6.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lsplant-6.4.aar",
          "url": "lsplant-6.4.aar",
          "size": 290658,
          "sha512": "cdc3d8ccc69a31c1bec652267d1a1bcc8ac1f679a1caebce477da7ec63acc7d9b7f80b2af117c9b2068f3574e0e46dd73f86715b75d3080b2e1a699947351cf8",
          "sha256": "5027989aebaf5471de4e4dcc5d05685a6fd9b1e6cea886f3a70eb8ae17fae3e1",
          "sha1": "11017632d6d1e2af4905bac25f0c029ea4c892b1",
          "md5": "ff5010082d1f51fb9e23cb715d95c74f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lsplant-6.4.aar",
          "url": "lsplant-6.4.aar",
          "size": 290658,
          "sha512": "cdc3d8ccc69a31c1bec652267d1a1bcc8ac1f679a1caebce477da7ec63acc7d9b7f80b2af117c9b2068f3574e0e46dd73f86715b75d3080b2e1a699947351cf8",
          "sha256": "5027989aebaf5471de4e4dcc5d05685a6fd9b1e6cea886f3a70eb8ae17fae3e1",
          "sha1": "11017632d6d1e2af4905bac25f0c029ea4c892b1",
          "md5": "ff5010082d1f51fb9e23cb715d95c74f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lsplant-6.4-sources.jar",
          "url": "lsplant-6.4-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lsplant-6.4-javadoc.jar",
          "url": "lsplant-6.4-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
